#!/bin/bash

n=5                   # number of files per command line

posts=(*.md)

for ((i=0; i < "${#posts[@]}"; i+=n)); do

    echo "$i.htm ------------------------"
    echo "    head"
        # each post
        for b in "${posts[@]:i:n}"; do
            echo "---divider---"
            echo "$b" 
        done
    echo "    foot"
    echo
        

        
done



