#!/bin/bash

n=6                   # number of files per command line; adjust to taste

readarray -t posts < <(for a in *.md; do echo "$a"; done | sort -r)

for ((i=0; i < "${#posts[@]}"; i+=n)); do

        echo "------------------------"
        echo "${posts[@]:i:n}" 
       # cat "${posts[@]:i:n}"
        
done


