#!/bin/bash

n=3                   # number of files per command line; adjust to taste

posts0=(*.md)          
readarray -t posts < <(for a in "${posts0[@]}"; do echo "$a"; done | sort -r)

for ((i=0; i < "${#posts[@]}"; i+=n)); do

        echo "------------------------"
        echo "${posts[@]:i:n}" 
       # cat "${posts[@]:i:n}"
        
done


